package com.tradevault.api;
import com.tradevault.model.*; import com.tradevault.repo.*; import com.tradevault.service.*;
import java.math.*; import java.time.*; import java.util.*;
import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api") public class ApiController {
 private final UserRepository users; private final TradeRepository trades; private final TradingFolderRepository folders; private final PasswordEncoder encoder; private final PasswordResetService resets; private final JwtService jwt; private final FinancialMathService math; private final StrategyRankingService rankings;
 public ApiController(UserRepository u,TradeRepository t,TradingFolderRepository f,PasswordEncoder e,PasswordResetService r,JwtService j,FinancialMathService m,StrategyRankingService s){users=u;trades=t;folders=f;encoder=e;resets=r;jwt=j;math=m;rankings=s;}
 record Credentials(String name,String email,String password){} record ResetRequest(String email,String code,String newPassword){} record FolderRequest(String name,String parentPath){} record TradeRequest(String tradeDate,String symbol,String side,BigDecimal quantity,BigDecimal entryPrice,BigDecimal exitPrice,BigDecimal leverage,BigDecimal feeRate,BigDecimal fixedCommission,BigDecimal riskPercent,String strategyName,String indicatorsUsed,String folderPath,String emotionTag,String screenshotData,String notes){} record PositionRequest(BigDecimal equity,BigDecimal riskPercent,BigDecimal entryPrice,BigDecimal stopPrice,BigDecimal leverage){}
 @PostMapping("/auth/signup") public ResponseEntity<?> signup(@RequestBody Credentials c){if(c.name()==null||c.name().isBlank()||c.email()==null||!c.email().contains("@")||c.password()==null||c.password().length()<6)return bad("Name, valid email and 6+ character password are required.");if(users.findByEmailIgnoreCase(c.email()).isPresent())return bad("An account already exists for this email.");return ResponseEntity.ok(session(users.save(new AppUser(c.name().trim(),c.email(),encoder.encode(c.password())))));}
 @PostMapping("/auth/login") public ResponseEntity<?> login(@RequestBody Credentials c){AppUser u=users.findByEmailIgnoreCase(c.email()==null?"":c.email()).orElse(null);if(u==null||!encoder.matches(c.password()==null?"":c.password(),u.getPasswordHash()))return ResponseEntity.status(401).body(Map.of("message","Invalid email or password."));return ResponseEntity.ok(session(u));}
 @PostMapping("/auth/forgot-password") public ResponseEntity<?> forgot(@RequestBody ResetRequest r){AppUser u=users.findByEmailIgnoreCase(r.email()==null?"":r.email()).orElse(null);try{if(u!=null)resets.sendCode(u);}catch(IllegalStateException e){return bad(e.getMessage());}return ResponseEntity.ok(Map.of("message","If that address belongs to an account, a reset code is on its way."));}
 @PostMapping("/auth/reset-password") public ResponseEntity<?> reset(@RequestBody ResetRequest r){AppUser u=users.findByEmailIgnoreCase(r.email()==null?"":r.email()).orElse(null);if(r.newPassword()==null||r.newPassword().length()<6||u==null||r.code()==null||!resets.reset(u,r.code(),r.newPassword()))return bad("That code is invalid or has expired.");users.save(u);return ResponseEntity.ok(Map.of("message","Password changed. You can sign in now."));}
 @GetMapping("/trades") public List<Trade> list(@RequestHeader("Authorization") String h){return trades.findByOwnerIdOrderByTradeDateDesc(current(h).getId());}
 @PostMapping("/trades") public ResponseEntity<?> add(@RequestHeader("Authorization") String h,@RequestBody TradeRequest r){try{if(r.symbol()==null||r.symbol().isBlank()||r.quantity()==null||r.entryPrice()==null||r.exitPrice()==null)return bad("Symbol, size, entry and exit are required.");if(r.screenshotData()!=null&&r.screenshotData().length()>3_000_000)return bad("Screenshot is too large. Please use an image below 2 MB.");BigDecimal lev=v(r.leverage(),BigDecimal.ONE);if(lev.compareTo(BigDecimal.ONE)<0||lev.compareTo(BigDecimal.valueOf(100))>0)return bad("Leverage must be between 1x and 100x.");BigDecimal risk=r.entryPrice().multiply(r.quantity()).multiply(v(r.riskPercent(),BigDecimal.ONE)).divide(BigDecimal.valueOf(100),8,RoundingMode.HALF_UP);Trade t=new Trade(current(h),r.tradeDate()==null?LocalDate.now():LocalDate.parse(r.tradeDate()),r.symbol(),"SHORT".equalsIgnoreCase(r.side())||"SELL".equalsIgnoreCase(r.side())?"SELL":"BUY",r.quantity(),r.entryPrice(),r.exitPrice(),lev,BigDecimal.ZERO,v(r.riskPercent(),BigDecimal.ONE),r.notes()==null?"":r.notes());var m=math.calculate(r.entryPrice(),r.exitPrice(),r.quantity(),"SELL".equals(t.getSide())?BigDecimal.ONE.negate():BigDecimal.ONE,v(r.feeRate(),new BigDecimal("0.0004")),v(r.fixedCommission(),BigDecimal.ZERO),risk);t.applyMath(m.grossPnl(),m.brokerageFee(),m.netPnl(),m.rMultiple());t.enrich(r.strategyName(),r.indicatorsUsed(),r.folderPath(),r.emotionTag());t.setScreenshotData(r.screenshotData());return ResponseEntity.status(201).body(trades.save(t));}catch(IllegalArgumentException e){return bad("Use a valid date in YYYY-MM-DD format.");}}
 @PutMapping("/trades/{id}") public ResponseEntity<?> update(@RequestHeader("Authorization") String h,@PathVariable Long id,@RequestBody TradeRequest r){try{AppUser owner=current(h);Trade t=trades.findById(id).filter(x->x.getOwner().getId().equals(owner.getId())).orElse(null);if(t==null)return ResponseEntity.status(HttpStatus.NOT_FOUND).body(Map.of("message","Trade not found."));if(r.symbol()==null||r.symbol().isBlank()||r.quantity()==null||r.entryPrice()==null||r.exitPrice()==null)return bad("Symbol, size, entry and exit are required.");if(r.screenshotData()!=null&&r.screenshotData().length()>3_000_000)return bad("Screenshot is too large. Please use an image below 2 MB.");BigDecimal lev=v(r.leverage(),BigDecimal.ONE);if(lev.compareTo(BigDecimal.ONE)<0||lev.compareTo(BigDecimal.valueOf(100))>0)return bad("Leverage must be between 1x and 100x.");BigDecimal risk=r.entryPrice().multiply(r.quantity()).multiply(v(r.riskPercent(),BigDecimal.ONE)).divide(BigDecimal.valueOf(100),8,RoundingMode.HALF_UP);String side="SHORT".equalsIgnoreCase(r.side())||"SELL".equalsIgnoreCase(r.side())?"SELL":"BUY";t.revise(r.tradeDate()==null?LocalDate.now():LocalDate.parse(r.tradeDate()),r.symbol(),side,r.quantity(),r.entryPrice(),r.exitPrice(),lev,v(r.riskPercent(),BigDecimal.ONE),r.notes()==null?"":r.notes());var m=math.calculate(r.entryPrice(),r.exitPrice(),r.quantity(),"SELL".equals(side)?BigDecimal.ONE.negate():BigDecimal.ONE,v(r.feeRate(),new BigDecimal("0.0004")),v(r.fixedCommission(),BigDecimal.ZERO),risk);t.applyMath(m.grossPnl(),m.brokerageFee(),m.netPnl(),m.rMultiple());t.enrich(r.strategyName(),r.indicatorsUsed(),r.folderPath(),r.emotionTag());t.setScreenshotData(r.screenshotData());return ResponseEntity.ok(trades.save(t));}catch(IllegalArgumentException e){return bad("Use a valid date in YYYY-MM-DD format.");}}
 @PostMapping("/risk/position-size") public Map<String,Object> size(@RequestBody PositionRequest r){BigDecimal s=math.positionSize(r.equity(),r.riskPercent(),r.entryPrice(),r.stopPrice(),r.leverage());return Map.of("positionSize",s,"notional",s.multiply(r.entryPrice()),"overLeveraged",r.leverage().compareTo(BigDecimal.valueOf(20))>0);}
 @GetMapping("/analytics") public Map<String,Object> analytics(@RequestHeader("Authorization") String h){List<Trade> ts=list(h);BigDecimal net=ts.stream().map(Trade::getNetPnl).reduce(BigDecimal.ZERO,BigDecimal::add),fees=ts.stream().map(Trade::getBrokerage).reduce(BigDecimal.ZERO,BigDecimal::add),win=ts.stream().filter(t->t.getNetPnl().signum()>0).map(Trade::getNetPnl).reduce(BigDecimal.ZERO,BigDecimal::add),loss=ts.stream().filter(t->t.getNetPnl().signum()<0).map(Trade::getNetPnl).reduce(BigDecimal.ZERO,BigDecimal::add).abs();long wins=ts.stream().filter(t->t.getNetPnl().signum()>0).count();return Map.of("accountEquity",BigDecimal.valueOf(100000).add(net),"netPnl",net,"brokerage",fees,"totalTrades",ts.size(),"activeTrades",0,"winRate",ts.isEmpty()?0:wins*100.0/ts.size(),"profitFactor",loss.signum()==0?win:win.divide(loss,2,RoundingMode.HALF_UP),"totalLeverage",ts.stream().map(Trade::getLeverage).reduce(BigDecimal.ZERO,BigDecimal::add),"maxRisk",ts.stream().map(Trade::getRiskPercent).max(Comparator.naturalOrder()).orElse(BigDecimal.ZERO),"strategyLeaderboard",rankings.rank(ts));}
 @GetMapping("/folders/{type}") public List<TradingFolder> folders(@RequestHeader("Authorization") String h,@PathVariable String type){return folders.findByOwnerIdAndTypeOrderByNameAsc(current(h).getId(),type.toUpperCase());}
 @PostMapping("/folders/{type}") public ResponseEntity<?> folder(@RequestHeader("Authorization") String h,@PathVariable String type,@RequestBody FolderRequest r){String normalized=type.toUpperCase();if(!normalized.equals("STRATEGY")&&!normalized.equals("INDICATOR"))return bad("Folder type must be strategy or indicator.");if(r.name()==null||r.name().isBlank())return bad("Folder name is required.");return ResponseEntity.status(201).body(folders.save(new TradingFolder(current(h),r.name().trim(),normalized,r.parentPath())));}
 private Map<String,Object> session(AppUser u){return Map.of("token",jwt.issue(u.getId(),u.getEmail()),"user",Map.of("name",u.getName(),"email",u.getEmail()));} private AppUser current(String h){try{return users.findById(jwt.userId(h.replace("Bearer ",""))).orElseThrow();}catch(Exception e){throw new org.springframework.web.server.ResponseStatusException(HttpStatus.UNAUTHORIZED,"Please sign in.");}} private BigDecimal v(BigDecimal x,BigDecimal d){return x==null?d:x;} private ResponseEntity<Map<String,String>> bad(String m){return ResponseEntity.badRequest().body(Map.of("message",m));}
}
