package com.tradevault.api;
import com.tradevault.model.*; import com.tradevault.repo.*; import com.tradevault.service.*;
import java.math.*; import java.time.*; import java.util.*; import java.util.stream.*;
import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api") public class ApiController {
 private final UserRepository users; private final TradeRepository trades; private final TradingFolderRepository folders; private final PasswordEncoder encoder; private final PasswordResetService resets; private final JwtService jwt; private final FinancialMathService math;
 public ApiController(UserRepository u,TradeRepository t,TradingFolderRepository f,PasswordEncoder e,PasswordResetService r,JwtService j,FinancialMathService m,StrategyRankingService ignored){users=u;trades=t;folders=f;encoder=e;resets=r;jwt=j;math=m;}
 record Credentials(String name,String email,String password){} record ResetRequest(String email,String code,String newPassword){} record FolderRequest(String name,String parentPath){} record AccountRequest(BigDecimal accountEquity){} record PositionRequest(BigDecimal equity,BigDecimal riskPercent,BigDecimal entryPrice,BigDecimal stopPrice,BigDecimal leverage){}
 record TradeRequest(String tradeDate,String symbol,String side,BigDecimal quantity,BigDecimal entryPrice,BigDecimal exitPrice,BigDecimal stopPrice,BigDecimal targetPrice,BigDecimal leverage,BigDecimal feeRate,BigDecimal fixedCommission,BigDecimal otherCharges,BigDecimal riskPercent,String strategyName,String indicatorsUsed,String folderPath,String emotionTag,String emotionDuring,String emotionAfter,Integer confidenceLevel,Boolean followedPlan,String timeframe,String marketSession,String tags,String mistakes,String lessons,String closingNotes,String screenshotData,String notes){}
 @PostMapping("/auth/signup") public ResponseEntity<?> signup(@RequestBody Credentials c){if(c.name()==null||c.name().isBlank()||c.email()==null||!c.email().contains("@")||c.password()==null||c.password().length()<6)return bad("Name, valid email and 6+ character password are required.");if(users.findByEmailIgnoreCase(c.email()).isPresent())return bad("An account already exists for this email.");return ResponseEntity.ok(session(users.save(new AppUser(c.name().trim(),c.email(),encoder.encode(c.password())))));}
 @PostMapping("/auth/login") public ResponseEntity<?> login(@RequestBody Credentials c){AppUser u=users.findByEmailIgnoreCase(c.email()==null?"":c.email()).orElse(null);if(u==null||!encoder.matches(c.password()==null?"":c.password(),u.getPasswordHash()))return ResponseEntity.status(401).body(Map.of("message","Invalid email or password."));return ResponseEntity.ok(session(u));}
 @PostMapping("/auth/forgot-password") public ResponseEntity<?> forgot(@RequestBody ResetRequest r){AppUser u=users.findByEmailIgnoreCase(r.email()==null?"":r.email()).orElse(null);try{if(u!=null)resets.sendCode(u);}catch(IllegalStateException e){return bad(e.getMessage());}return ResponseEntity.ok(Map.of("message","If that address belongs to an account, a reset code is on its way."));}
 @PostMapping("/auth/reset-password") public ResponseEntity<?> reset(@RequestBody ResetRequest r){AppUser u=users.findByEmailIgnoreCase(r.email()==null?"":r.email()).orElse(null);if(r.newPassword()==null||r.newPassword().length()<6||u==null||r.code()==null||!resets.reset(u,r.code(),r.newPassword()))return bad("That code is invalid or has expired.");users.save(u);return ResponseEntity.ok(Map.of("message","Password changed. You can sign in now."));}
 @GetMapping("/trades") public List<Trade> list(@RequestHeader("Authorization") String h){return trades.findByOwnerIdOrderByTradeDateDesc(current(h).getId());}
 @PostMapping("/trades") public ResponseEntity<?> add(@RequestHeader("Authorization") String h,@RequestBody TradeRequest r){try{return ResponseEntity.status(201).body(trades.save(build(new Trade(current(h),date(r),r.symbol(),side(r),r.quantity(),r.entryPrice(),r.exitPrice(),leverage(r),BigDecimal.ZERO,riskPercent(r),text(r.notes())),r)));}catch(IllegalArgumentException e){return bad(e.getMessage());}}
 @PutMapping("/trades/{id}") public ResponseEntity<?> update(@RequestHeader("Authorization") String h,@PathVariable Long id,@RequestBody TradeRequest r){try{AppUser u=current(h);Trade t=trades.findById(id).filter(x->x.getOwner().getId().equals(u.getId())).orElse(null);if(t==null)return ResponseEntity.status(404).body(Map.of("message","Trade not found."));t.revise(date(r),required(r.symbol(),"Symbol"),side(r),required(r.quantity(),"Position size"),required(r.entryPrice(),"Entry price"),r.exitPrice(),leverage(r),riskPercent(r),text(r.notes()));return ResponseEntity.ok(trades.save(build(t,r)));}catch(IllegalArgumentException e){return bad(e.getMessage());}}
 private Trade build(Trade t,TradeRequest r){if(r.screenshotData()!=null&&r.screenshotData().length()>3_000_000)throw new IllegalArgumentException("Screenshot is too large. Please use an image below 2 MB.");BigDecimal risk=r.stopPrice()==null?t.getEntryPrice().multiply(t.getQuantity()).multiply(riskPercent(r)).divide(BigDecimal.valueOf(100),8,RoundingMode.HALF_UP):t.getEntryPrice().subtract(r.stopPrice()).abs().multiply(t.getQuantity());if(r.exitPrice()!=null){var m=math.calculate(t.getEntryPrice(),r.exitPrice(),t.getQuantity(),"SELL".equals(t.getSide())?BigDecimal.ONE.negate():BigDecimal.ONE,value(r.feeRate(),new BigDecimal("0.0004")),value(r.fixedCommission(),BigDecimal.ZERO).add(value(r.otherCharges(),BigDecimal.ZERO)),risk);t.applyMath(m.grossPnl(),m.brokerageFee(),m.netPnl(),m.rMultiple());}t.enrich(r.strategyName(),r.indicatorsUsed(),r.folderPath(),r.emotionTag());t.enrichDetails(r.stopPrice(),r.targetPrice(),r.otherCharges(),r.closingNotes(),r.timeframe(),r.marketSession(),r.tags(),r.mistakes(),r.lessons(),r.emotionDuring(),r.emotionAfter(),r.confidenceLevel(),r.followedPlan());t.setScreenshotData(r.screenshotData());return t;}
 @GetMapping("/account") public Map<String,Object> account(@RequestHeader("Authorization") String h){return Map.of("accountEquity",current(h).getAccountEquity(),"currency","INR");}
 @PutMapping("/account") public ResponseEntity<?> account(@RequestHeader("Authorization") String h,@RequestBody AccountRequest r){if(r.accountEquity()==null||r.accountEquity().signum()<0)return bad("Account equity must be zero or greater.");AppUser u=current(h);u.setAccountEquity(r.accountEquity());users.save(u);return ResponseEntity.ok(Map.of("accountEquity",u.getAccountEquity(),"currency","INR"));}
 @PostMapping("/risk/position-size") public Map<String,Object> size(@RequestBody PositionRequest r){BigDecimal s=math.positionSize(r.equity(),r.riskPercent(),r.entryPrice(),r.stopPrice(),r.leverage());return Map.of("positionSize",s,"notional",s.multiply(r.entryPrice()),"riskAmount",r.equity().multiply(r.riskPercent()).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP),"overLeveraged",r.leverage().compareTo(BigDecimal.valueOf(20))>0);}
 @GetMapping("/analytics") public Map<String,Object> analytics(@RequestHeader("Authorization") String h){AppUser u=current(h);return metrics(list(h),u.getAccountEquity());}
 @GetMapping("/dashboard") public Map<String,Object> dashboard(@RequestHeader("Authorization") String h){AppUser u=current(h);List<Trade> ownerTrades=trades.findByOwnerIdOrderByTradeDateDesc(u.getId());return Map.of("trades",ownerTrades,"analytics",metrics(ownerTrades,u.getAccountEquity()),"strategyFolders",folders.findByOwnerIdAndTypeOrderByNameAsc(u.getId(),"STRATEGY"),"indicatorFolders",folders.findByOwnerIdAndTypeOrderByNameAsc(u.getId(),"INDICATOR"));}
 @GetMapping("/analytics/strategy/{name}") public Map<String,Object> strategy(@RequestHeader("Authorization") String h,@PathVariable String name){return metrics(list(h).stream().filter(t->Objects.equals(t.getStrategyName(),name)).toList(),current(h).getAccountEquity());}
 @GetMapping("/analytics/indicator/{name}") public Map<String,Object> indicator(@RequestHeader("Authorization") String h,@PathVariable String name){return metrics(list(h).stream().filter(t->Objects.equals(t.getIndicatorsUsed(),name)).toList(),current(h).getAccountEquity());}
 private Map<String,Object> metrics(List<Trade> all,BigDecimal equity){List<Trade> closed=all.stream().filter(t->"CLOSED".equals(t.getStatus())).toList();BigDecimal net=sum(closed,Trade::getNetPnl),fees=closed.stream().map(t->t.getBrokerage().add(t.getOtherCharges())).reduce(BigDecimal.ZERO,BigDecimal::add),grossProfit=closed.stream().map(Trade::getNetPnl).filter(x->x.signum()>0).reduce(BigDecimal.ZERO,BigDecimal::add),grossLoss=closed.stream().map(Trade::getNetPnl).filter(x->x.signum()<0).reduce(BigDecimal.ZERO,BigDecimal::add).abs();long wins=closed.stream().filter(t->t.getNetPnl().signum()>0).count();Map<String,Object> m=new LinkedHashMap<>();m.put("accountEquity",equity.add(net));m.put("netPnl",net);m.put("brokerage",fees);m.put("totalCharges",fees);m.put("totalTrades",all.size());m.put("activeTrades",all.size()-closed.size());m.put("closedTrades",closed.size());m.put("winRate",closed.isEmpty()?0:wins*100.0/closed.size());m.put("profitFactor",grossLoss.signum()==0?grossProfit:grossProfit.divide(grossLoss,2,RoundingMode.HALF_UP));m.put("grossProfit",grossProfit);m.put("grossLoss",grossLoss);m.put("bestTrade",closed.stream().map(Trade::getNetPnl).max(Comparator.naturalOrder()).orElse(BigDecimal.ZERO));m.put("worstTrade",closed.stream().map(Trade::getNetPnl).min(Comparator.naturalOrder()).orElse(BigDecimal.ZERO));m.put("strategyLeaderboard",group(all,Trade::getStrategyName));m.put("indicatorLeaderboard",group(all,Trade::getIndicatorsUsed));return m;}
 private List<Map<String,Object>> group(List<Trade> ts,java.util.function.Function<Trade,String> key){return ts.stream().collect(Collectors.groupingBy(t->{String n=key.apply(t);return n==null||n.isBlank()?"Unassigned":n;})).entrySet().stream().map(e->Map.<String,Object>of("name",e.getKey(),"trades",e.getValue().size(),"netPnl",sum(e.getValue(),Trade::getNetPnl))).sorted((a,b)->((BigDecimal)b.get("netPnl")).compareTo((BigDecimal)a.get("netPnl"))).toList();}
 @GetMapping("/folders/{type}") public List<TradingFolder> folders(@RequestHeader("Authorization") String h,@PathVariable String type){return folders.findByOwnerIdAndTypeOrderByNameAsc(current(h).getId(),type.toUpperCase());}
 @PostMapping("/folders/{type}") public ResponseEntity<?> folder(@RequestHeader("Authorization") String h,@PathVariable String type,@RequestBody FolderRequest r){String n=type.toUpperCase();if(!n.equals("STRATEGY")&&!n.equals("INDICATOR"))return bad("Folder type must be strategy or indicator.");if(r.name()==null||r.name().isBlank())return bad("Folder name is required.");return ResponseEntity.status(201).body(folders.save(new TradingFolder(current(h),r.name().trim(),n,r.parentPath())));}
 @PutMapping("/folders/{id}") public ResponseEntity<?> renameFolder(@RequestHeader("Authorization") String h,@PathVariable Long id,@RequestBody FolderRequest r){TradingFolder f=folders.findByIdAndOwnerId(id,current(h).getId()).orElse(null);if(f==null)return ResponseEntity.status(404).body(Map.of("message","Folder not found."));if(r.name()==null||r.name().isBlank())return bad("Folder name is required.");f.rename(r.name(),r.parentPath());return ResponseEntity.ok(folders.save(f));}
 @DeleteMapping("/folders/{id}") public ResponseEntity<?> deleteFolder(@RequestHeader("Authorization") String h,@PathVariable Long id){TradingFolder f=folders.findByIdAndOwnerId(id,current(h).getId()).orElse(null);if(f==null)return ResponseEntity.status(404).body(Map.of("message","Folder not found."));folders.delete(f);return ResponseEntity.noContent().build();}
 private BigDecimal sum(List<Trade> ts,java.util.function.Function<Trade,BigDecimal> f){return ts.stream().map(f).reduce(BigDecimal.ZERO,BigDecimal::add);} private LocalDate date(TradeRequest r){return r.tradeDate()==null?LocalDate.now():LocalDate.parse(r.tradeDate());} private String side(TradeRequest r){return "SHORT".equalsIgnoreCase(r.side())||"SELL".equalsIgnoreCase(r.side())?"SELL":"BUY";} private BigDecimal leverage(TradeRequest r){BigDecimal x=value(r.leverage(),BigDecimal.ONE);if(x.compareTo(BigDecimal.ONE)<0||x.compareTo(BigDecimal.valueOf(100))>0)throw new IllegalArgumentException("Leverage must be between 1x and 100x.");return x;} private BigDecimal riskPercent(TradeRequest r){return value(r.riskPercent(),BigDecimal.ONE);} private String text(String s){return s==null?"":s;} private <T>T required(T x,String n){if(x==null||(x instanceof String s&&s.isBlank()))throw new IllegalArgumentException(n+" is required.");return x;} private BigDecimal value(BigDecimal x,BigDecimal d){return x==null?d:x;} private Map<String,Object> session(AppUser u){return Map.of("token",jwt.issue(u.getId(),u.getEmail()),"user",Map.of("name",u.getName(),"email",u.getEmail()));} private AppUser current(String h){try{return users.findById(jwt.userId(h.replace("Bearer ",""))).orElseThrow();}catch(Exception e){throw new org.springframework.web.server.ResponseStatusException(HttpStatus.UNAUTHORIZED,"Please sign in.");}} private ResponseEntity<Map<String,String>> bad(String m){return ResponseEntity.badRequest().body(Map.of("message",m));}
}
