package com.tradevault.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;

@Entity
public class Trade {
  @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;
  @ManyToOne(optional=false) private AppUser owner;
  private LocalDate tradeDate; private LocalDate closeDate; private String symbol; private String side; private BigDecimal quantity; private BigDecimal entryPrice; private BigDecimal exitPrice; private BigDecimal stopPrice; private BigDecimal targetPrice;
  private BigDecimal leverage; private BigDecimal brokerage; private BigDecimal otherCharges; private BigDecimal riskPercent; private BigDecimal grossPnl; private BigDecimal netPnl; private BigDecimal rMultiple;
  private String status="RUNNING"; private String strategyName; private String indicatorsUsed; private String folderPath; private String emotionTag; private String emotionDuring; private String emotionAfter; private Integer confidenceLevel; private Boolean followedPlan; @Lob private String screenshotData; @Lob private String notes; @Lob private String closingNotes; private String timeframe; private String marketSession; private String tags; private String mistakes; private String lessons;
  protected Trade() {}
  public Trade(AppUser owner, LocalDate date, String symbol, String side, BigDecimal quantity, BigDecimal entry, BigDecimal exit, BigDecimal leverage, BigDecimal brokerage, BigDecimal risk, String notes) {
    this.owner=owner; tradeDate=date; this.symbol=symbol.toUpperCase(); this.side=side.toUpperCase(); this.quantity=quantity; entryPrice=entry; exitPrice=exit; this.leverage=leverage; this.brokerage=brokerage; riskPercent=risk; this.notes=notes;
    if(exit==null){grossPnl=BigDecimal.ZERO;netPnl=BigDecimal.ZERO; rMultiple=BigDecimal.ZERO;status="RUNNING";}else{grossPnl=exit.subtract(entry).multiply(quantity).multiply("SELL".equals(this.side)?BigDecimal.valueOf(-1):BigDecimal.ONE); netPnl=grossPnl.subtract(brokerage); rMultiple=BigDecimal.ZERO;status="CLOSED";closeDate=date;}
  }
  public void applyMath(BigDecimal gross, BigDecimal fee, BigDecimal net, BigDecimal r){grossPnl=gross; brokerage=fee; netPnl=net; rMultiple=r;}
  public void revise(LocalDate date,String symbol,String side,BigDecimal quantity,BigDecimal entry,BigDecimal exit,BigDecimal leverage,BigDecimal risk,String notes){tradeDate=date;this.symbol=symbol.toUpperCase();this.side=side.toUpperCase();this.quantity=quantity;entryPrice=entry;exitPrice=exit;this.leverage=leverage;riskPercent=risk;this.notes=notes;status=exit==null?"RUNNING":"CLOSED";if(exit==null){grossPnl=BigDecimal.ZERO;netPnl=BigDecimal.ZERO;brokerage=BigDecimal.ZERO;rMultiple=BigDecimal.ZERO;}else closeDate=date;}
  public void enrich(String strategy,String indicators,String path,String emotion){strategyName=strategy;indicatorsUsed=indicators;folderPath=path;emotionTag=emotion;}
  public void enrichDetails(BigDecimal stop,BigDecimal target,BigDecimal charges,String closing,String timeframe,String session,String tags,String mistakes,String lessons,String during,String after,Integer confidence,Boolean followed){stopPrice=stop;targetPrice=target;otherCharges=charges==null?BigDecimal.ZERO:charges;closingNotes=closing;this.timeframe=timeframe;marketSession=session;this.tags=tags;this.mistakes=mistakes;this.lessons=lessons;emotionDuring=during;emotionAfter=after;confidenceLevel=confidence;followedPlan=followed;}
  public void setScreenshotData(String screenshotData){this.screenshotData=screenshotData;}
  public Long getId(){return id;} public AppUser getOwner(){return owner;} public LocalDate getTradeDate(){return tradeDate;} public LocalDate getCloseDate(){return closeDate;} public String getSymbol(){return symbol;} public String getSide(){return side;} public BigDecimal getQuantity(){return quantity;} public BigDecimal getEntryPrice(){return entryPrice;} public BigDecimal getExitPrice(){return exitPrice;} public BigDecimal getStopPrice(){return stopPrice;} public BigDecimal getTargetPrice(){return targetPrice;} public BigDecimal getLeverage(){return leverage;} public BigDecimal getBrokerage(){return brokerage==null?BigDecimal.ZERO:brokerage;} public BigDecimal getOtherCharges(){return otherCharges==null?BigDecimal.ZERO:otherCharges;} public BigDecimal getRiskPercent(){return riskPercent==null?BigDecimal.ZERO:riskPercent;} public BigDecimal getGrossPnl(){return grossPnl==null?BigDecimal.ZERO:grossPnl;} public BigDecimal getNetPnl(){return netPnl==null?BigDecimal.ZERO:netPnl;} public BigDecimal getRMultiple(){return rMultiple==null?BigDecimal.ZERO:rMultiple;} public String getStatus(){return status==null?(exitPrice==null?"RUNNING":"CLOSED"):status;} public String getStrategyName(){return strategyName;} public String getIndicatorsUsed(){return indicatorsUsed;} public String getFolderPath(){return folderPath;} public String getEmotionTag(){return emotionTag;} public String getEmotionDuring(){return emotionDuring;} public String getEmotionAfter(){return emotionAfter;} public Integer getConfidenceLevel(){return confidenceLevel;} public Boolean getFollowedPlan(){return followedPlan;} public String getScreenshotData(){return screenshotData;} public String getNotes(){return notes;} public String getClosingNotes(){return closingNotes;} public String getTimeframe(){return timeframe;} public String getMarketSession(){return marketSession;} public String getTags(){return tags;} public String getMistakes(){return mistakes;} public String getLessons(){return lessons;}
}
